namespace Storj_Tools
{
    [default_interface]
    runtimeclass Node 
    {
        Node();
        String Name;
        String Path;
        String SVersion;
        UInt32 DStatus;
        String HStatus{ get; };
        String StatusIcon{ get; };
        Microsoft.UI.Xaml.Media.SolidColorBrush StatusColor{ get; };
        Boolean IsStartButtonEnabled();
    }
}
