import "StorjData.idl";

namespace Storj_Tools
{
    [default_interface]
    runtimeclass ServicePage : Microsoft.UI.Xaml.Controls.Page
    {
        ServicePage();
        StorjData StorjData{ get; };
    }
}
