import "Node.idl"; // Pøidejte tento øádek

namespace Storj_Tools
{	
    [default_interface]
    runtimeclass StorjData : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        StorjData();

        // Main page
        String ServiceStatus{ get; };
		Microsoft.UI.Xaml.Media.SolidColorBrush ServiceStatusColor{ get; };
		void RestartService();

		// Setting from YAML file
		void SaveSettings();
		void LoadSettings();

        // Service page
		Single UpdateNodeInterval;
		Single CheckNodeInterval;
		Single LogReductionInterval;
		Single LogReductionMaxSize;
		Single LogReducedSize;

		// Discord page
		String BotToken;
		String UserID;
		void SendTestMessageToDiscord();

		// Node page
		Windows.Foundation.Collections.IObservableVector<Storj_Tools.Node> Nodes();
		void UpdateNodes();
		void StartNodeService(String nodeName);
        
        // Settings page
		void InitTheme();
		Boolean IsLightMode;
		Microsoft.UI.Xaml.ElementTheme CurrentTheme;
		Single UpdateNodeUIInterval;
	}
}
